kind: pipeline
name: abnf
steps:
- name: unit-test
  image: golang:1.15
  commands:
  - go test -race -cover -covermode=atomic -coverprofile=coverage.out ./...
- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
    - coverage.out
